name: "Dee's Daily Musings"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2674
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090909'
    - '#28292d'
    - '#c5c4c9'
    - '#424347'
    - '#929398'
  brandStrength: 0.5102411035913974
  lightness: 0.6282785313669592
  saturation: 0.7651847170200199
  rhythmicContrast: 0.5
purpose: []
